ALTER TABLE payments ADD COLUMN IF NOT EXISTS invoice_html TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS refund_id VARCHAR(100);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS refunded_at TIMESTAMP;
